# Generated by Django 5.1.3 on 2024-11-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_friends_profile_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Jinx: The Loose Cannon, a chaotic marksman with explosive weapons.'),
        ),
    ]
