# Generated by Django 5.1.3 on 2024-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Yasuo: The Unforgiven, a swordsman with wind-based abilities and a powerful ultimate.'),
        ),
    ]
