# Generated by Django 5.1.3 on 2024-12-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_alter_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Jinx: The Loose Cannon, a chaotic marksman with explosive weapons.'),
        ),
    ]
