# Generated by Django 5.1.2 on 2024-10-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_leaderboardentry_opponent_party_num_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='num_players',
            field=models.IntegerField(choices=[(1, 'Play with AI'), (2, '2 Players'), (3, '3 Players')], default=2),
        ),
    ]
