# Generated by Django 5.1.3 on 2024-11-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_tournamentmatch_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='num_players',
            field=models.IntegerField(choices=[(0, 'Play Local'), (1, 'Play with AI'), (2, '2 Players'), (3, '3 Players')], default=2),
        ),
    ]
