# Generated by Django 5.1.3 on 2024-11-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_room_users_room_user1_room_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(db_default='room_cdb03311e84c45b68df470871ba3642f', max_length=200),
        ),
    ]
