# Generated by Django 5.1.3 on 2024-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(db_default="'Room '+ currval('chat_room_id_seq')", max_length=200),
        ),
    ]
