# Generated by Django 5.1.3 on 2024-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_room_name_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(),
        ),
    ]
